version: "3"
services:
  pkdxapimongo:
    image: mongo:latest
    container_name: "pkdxapimongo"
    ports:
      - 27018:27017
  pkdxapi:
    image: pkdxapi
    container_name: pkdxapi
    ports:
      - 8080:8080
    links:
      - pkdxapimongo
